Add `delta` parameters to sliders
peterhinch/micropython-micro-gui pull request #20
Opened 2022-09-11 08:43 UTC by Leonti

2022-09-11 13:04 UTC, peterhinch commented on gui/widgets/sliders.py
> +            min_delta = min_delta, max_delta = max_delta)
There is no need to specify the parameter name here. For consistency please treat the args as per other args:
```python
... prcolor, min_delta, max_delta)
```
(for both sliders).

2022-09-11 13:05 UTC, peterhinch requested changes
I'm OK with this, subject to my comment on args.

2022-09-11 14:06 UTC, Leonti commented on gui/widgets/sliders.py
> +            min_delta = min_delta, max_delta = max_delta)
Done! :+1:

2022-09-12 07:23 UTC, merged

2022-09-12 07:23 UTC, peterhinch commented
Thank you.